#+title: Intro
#+OPTIONS: toc:nil

* Why Number Theory?
So, this semester, I'm enrolled in [[https://www.math.purdue.edu/~twooley/2025nt/2025nt.html][a course on Number Theory]] with the amazing [[https://www.math.purdue.edu/~twooley/][Prof. Wooley]]. I've always been fascinated by the subject, but never really had the chance to study it in depth. I'm really excited to learn more about it, and I thought it would be a good idea to document my journey through the course.

** What will I include here?
I will be taking notes in class (in org-mode): so I thought it would be a good idea to publish them. I will also be solving problems from the textbook, and I will include my solutions here. I will also include any interesting facts or theorems that I come across.

** Why am I doing this?
I think that writing about what I learn will help me understand the material better. I also think that it will be a good way to keep myself accountable in taking notes. I'm sure that proofreading my notes will also help me catch any mistakes that I make.

* What Now?
But yeah, that's about it. I'm really excited to get started with this course, and I hope that you enjoy reading my notes!
