#+title: 1. Motivation
#+OPTIONS: toc:nil

* Why Number Theory?

Short answer: it's fun! please don't ask me why.

Long answer follows.

* Open Problems
** Egyptian fractions
Is it true that for all integers \( n \geq 2 \), there exist \( x, y, z \in \mathbb{N} \) satisfying,

\[ \frac{4}{n} = \frac{1}{x} + \frac{1}{y} + \frac{1}{z} \]

** Riemann Hypothesis
Is is true that when \( x \) is large enough, then

\[ | \{p \leq x : p \text{ is prime} \}| - \int_2^x \frac{dt}{\log t} < x^{\frac{1}{2}} (\log x)^{100000} \]

** Mersenne Primes
Show that there are infinitely many primes of the form \( 2^p - 1 \) (with \( p \) prime)?

** Generalised Fermat Problem
Is it true that the equation \( x^n + y^n = z^n + w^n \) has no integer solutions \( x, y, z, w, n \geq 5 \), other than the "obvious" solutions?

** Odd Perfect Numbers
Do there exist odd perfect numbers?

- (Perfect number \( n \) has the property that the sum of its proper divisors is equal to \( n \))
   - If \( n \) is odd and perfect, then \( n > 10^{1500} \) and has \( \geq \) 101 prime factors and \( \geq \) 10 distinct prime factors.
